import type { Dictionary } from 'types/common';
import type { AttributeCard } from '../types/common';

export const VOCAL_COLORS: Record<string, AttributeCard> = {
  STANDARD: {
    id: 'STANDARD',
    name: 'Standard',
    type: 'vocalColor',
    group: 'vocal',
    description: 'A balanced and versatile voice that serves as the reliable backbone for any group harmony.',
    occurrence: 35,
    influences: { 'aggregations.audienceRatio': 0.05 },
  },
  SWEET: {
    id: 'SWEET',
    name: 'Sweet',
    type: 'vocalColor',
    group: 'vocal',
    description: "A light, 'honey-like' vocal tone that instantly captures the public's heart.",
    occurrence: 15,
    influences: {
      'personality.gentleness': 3,
      'personality.sensitivity': 2,
      'aggregations.fanbaseRatio': 0.085,
    },
  },
  HIGH_PITCH: {
    id: 'HIGH_PITCH',
    name: 'High Pitch',
    type: 'vocalColor',
    group: 'vocal',
    description: "The 'Power Vocal' archetype capable of hitting piercing high notes.",
    occurrence: 10,
    influences: {
      'coreSkills.vocals': 0.5,
      'personality.ambition': 2,
      'utilitySkills.stamina': -1,
      'aggregations.audienceRatio': 0.09,
    },
  },
  HUSKY: {
    id: 'HUSKY',
    name: 'Husky',
    type: 'vocalColor',
    group: 'vocal',
    description: 'A textured, soulful rasp that adds a layer of maturity.',
    occurrence: 10,
    influences: {
      'personality.maturity': 3,
      'coreSkills.uniqueness': 0.3,
      'aggregations.fanbaseRatio': 0.08,
    },
  },
  VELVET: {
    id: 'VELVET',
    name: 'Velvet',
    type: 'vocalColor',
    group: 'vocal',
    description: 'A smooth, R&B-leaning voice that feels intimate and sophisticated.',
    occurrence: 10,
    influences: {
      'personality.extroversion': -2,
      'personality.sincerity': 2,
      'aggregations.fanbaseRatio': 0.075,
    },
  },
  GRITTY: {
    id: 'GRITTY',
    name: 'Gritty',
    type: 'vocalColor',
    group: 'vocal',
    description: 'A raw, rock-influenced edge that conveys high emotion.',
    occurrence: 10,
    influences: {
      'personality.gentleness': -3,
      'personality.resilience': 3,
      'coreSkills.vocals': 0.2,
      'aggregations.fanbaseRatio': 0.06,
    },
  },
  DEEP_BASS: {
    id: 'DEEP_BASS',
    name: 'Deep Bass',
    type: 'vocalColor',
    group: 'vocal',
    description: 'A rare, resonant low range used for dramatic impact.',
    occurrence: 10,
    influences: {
      'personality.extroversion': -3,
      'coreSkills.uniqueness': 0.5,
      'aggregations.fanbaseRatio': 0.07,
    },
  },
};

export const DANCE_STYLES: Record<string, AttributeCard> = {
  URBAN: {
    id: 'URBAN',
    name: 'Urban',
    occurrence: 45,
    type: 'danceStyle',
    group: 'dance',
    description: 'The industry standard for synchronized choreography.',
    influences: {
      'utilitySkills.consistency': 1,
      'aggregations.audienceRatio': 0.06,
    },
  },
  SMOOTH: {
    id: 'SMOOTH',
    name: 'Smooth',
    type: 'danceStyle',
    group: 'dance',
    description: 'A natural groover who makes difficult movement look effortless.',
    occurrence: 20,
    influences: {
      'coreSkills.stagePresence': 0.4,
      'personality.discipline': -2,
      'aggregations.audienceRatio': 0.08,
    },
  },
  POPPING: {
    id: 'POPPING',
    name: 'Popping',
    type: 'danceStyle',
    group: 'dance',
    occurrence: 10,
    description: 'Technical mastery of isolations and sharp hits.',
    influences: {
      'utilitySkills.learning': 1,
      'personality.discipline': 3,
      'aggregations.fanbaseRatio': 0.07,
    },
  },
  B_BOY: {
    id: 'B_BOY',
    name: 'B Boy',
    type: 'danceStyle',
    group: 'dance',
    description: 'Street-dance specialist; high-risk but high-reward.',
    occurrence: 5,
    influences: {
      'utilitySkills.acrobatics': 1,
      'personality.ambition': 3,
      'conditions.physicalCondition': -5,
      'aggregations.productionRatio': 0.085,
    },
  },
  ACROBATIC: {
    id: 'ACROBATIC',
    name: 'Acrobatic',
    type: 'danceStyle',
    group: 'dance',
    description: 'Featuring flips and stunts that drive a live crowd into a frenzy.',
    occurrence: 10,
    influences: {
      'utilitySkills.stamina': 1,
      'utilitySkills.acrobatics': 2,
      'personality.resilience': 4,
      'aggregations.productionRatio': 0.095,
    },
  },
  LYRICAL: {
    id: 'LYRICAL',
    name: 'Lyrical',
    type: 'danceStyle',
    group: 'dance',
    description: 'Focuses on storytelling through fluid movement.',
    occurrence: 10,
    influences: {
      'personality.sensitivity': 5,
      'personality.maturity': 2,
      'aggregations.fanbaseRatio': 0.065,
    },
  },
};

export const RAP_STYLES: Record<string, AttributeCard> = {
  BASIC: {
    id: 'BASIC',
    name: 'Basic',
    type: 'rapStyle',
    group: 'rap',
    description: 'Standard rhythmic delivery.',
    occurrence: 40,
    influences: { 'aggregations.audienceRatio': 0.04 },
  },
  SWAG: {
    id: 'SWAG',
    name: 'Swag',
    type: 'rapStyle',
    group: 'rap',
    description: "Emphasis on aura, tone, and 'effortless cool'.",
    occurrence: 15,
    influences: {
      'personality.gentleness': -4,
      'personality.extroversion': 4,
      'aggregations.productionRatio': 0.085,
    },
  },
  TECHNICAL: {
    id: 'TECHNICAL',
    name: 'Technical',
    type: 'rapStyle',
    group: 'rap',
    description: "The 'Fast-Tongue' specialist proving skill through speed.",
    occurrence: 10,
    influences: {
      'personality.discipline': 4,
      'utilitySkills.memory': 1,
      'aggregations.audienceRatio': 0.09,
    },
  },
  FLOW: {
    id: 'FLOW',
    name: 'Flow',
    type: 'rapStyle',
    group: 'rap',
    description: 'Focuses on rhythmic complexity and internal rhymes.',
    occurrence: 10,
    influences: {
      'personality.curiosity': 3,
      'coreSkills.rap': 0.3,
      'aggregations.fanbaseRatio': 0.075,
    },
  },
  MELODIC: {
    id: 'MELODIC',
    name: 'Melodic',
    type: 'rapStyle',
    group: 'rap',
    description: 'Blends singing and rhyming.',
    occurrence: 10,
    influences: {
      'personality.gentleness': 3,
      'personality.sensitivity': 3,
      'coreSkills.vocals': 0.2,
      'aggregations.audienceRatio': 0.08,
    },
  },
  CLASSIC: {
    id: 'CLASSIC',
    name: 'Classic',
    type: 'rapStyle',
    group: 'rap',
    description: "A student of 'old-school' boom-bap.",
    occurrence: 10,
    influences: {
      'personality.maturity': 4,
      'personality.sincerity': 3,
      'aggregations.fanbaseRatio': 0.06,
    },
  },
  GRITTY: {
    id: 'GRITTY',
    name: 'Gritty',
    type: 'rapStyle',
    group: 'rap',
    description: 'Aggressive, underground-inspired delivery.',
    occurrence: 5,
    influences: {
      'personality.gentleness': -5,
      'personality.resilience': 5,
      'aggregations.fanbaseRatio': 0.055,
    },
  },
};

export const VISUAL_VIBES: Record<string, AttributeCard> = {
  WARM: {
    id: 'WARM',
    name: 'Warm',
    type: 'visualVibe',
    group: 'visual',
    occurrence: 30,
    description: 'The neighbor next door—approachable and kind.',
    influences: {
      'personality.gentleness': 4,
      'aggregations.contestantsLikeness': 0.075,
    },
  },
  CUTE: {
    id: 'CUTE',
    name: 'Cute',
    type: 'visualVibe',
    group: 'visual',
    occurrence: 25,
    description: "The 'Cutie' machine; a youthful and bright look.",
    influences: {
      'personality.maturity': -5,
      'personality.extroversion': 5,
      'aggregations.fanbaseRatio': 0.09,
    },
  },
  MASCULINE: {
    id: 'MASCULINE',
    name: 'Masculine',
    type: 'visualVibe',
    group: 'visual',
    occurrence: 20,
    description: 'Sharp features and an athletic build.',
    influences: {
      'personality.ambition': 3,
      'utilitySkills.stamina': 1,
      'aggregations.audienceRatio': 0.085,
    },
  },
  CHIC: {
    id: 'CHIC',
    name: 'Chic',
    type: 'visualVibe',
    group: 'visual',
    occurrence: 10,
    description: 'High-fashion and striking; often edited as cold.',
    influences: {
      'personality.extroversion': -4,
      'personality.sincerity': -2,
      'coreSkills.visual': 0.5,
      'aggregations.productionRatio': 0.07,
    },
  },
  MYSTERIOUS: {
    id: 'MYSTERIOUS',
    name: 'Mysterious',
    type: 'visualVibe',
    group: 'visual',
    occurrence: 15,
    description: 'A quiet, intense aura that draws people in.',
    influences: {
      'personality.extroversion': -8,
      'coreSkills.uniqueness': 0.8,
      'aggregations.fanbaseRatio': 0.065,
    },
  },
};

export const LEADERSHIP_STYLES: Record<string, AttributeCard> = {
  COMMANDER: {
    id: 'COMMANDER',
    name: 'Commander',
    type: 'leadershipStyle',
    group: 'leadership',
    description: 'A strict, results-oriented leader.',
    occurrence: 15,
    influences: {
      'personality.discipline': 6,
      'personality.gentleness': -4,
      'coreSkills.leadership': 0.8,
      'aggregations.productionRatio': 0.06,
    },
  },
  CARETAKER: {
    id: 'CARETAKER',
    name: 'Caretaker',
    type: 'leadershipStyle',
    group: 'leadership',
    description: 'Leads through empathy and emotional support.',
    occurrence: 15,
    influences: {
      'personality.gentleness': 6,
      'personality.sensitivity': 4,
      'conditions.mentalCondition': 10,
      'aggregations.contestantsLikeness': 0.085,
    },
  },
  VISIONARY: {
    id: 'VISIONARY',
    name: 'Visionary',
    type: 'leadershipStyle',
    group: 'leadership',
    description: 'Leads by example on stage with sheer charisma.',
    occurrence: 15,
    influences: {
      'utilitySkills.charisma': 1,
      'coreSkills.stagePresence': 0.5,
      'aggregations.audienceRatio': 0.09,
    },
  },
  DIPLOMAT: {
    id: 'DIPLOMAT',
    name: 'Diplomat',
    type: 'leadershipStyle',
    group: 'leadership',
    description: 'A democratic leader who seeks consensus.',
    occurrence: 20,
    influences: {
      'personality.sincerity': 5,
      'personality.maturity': 4,
      'coreSkills.leadership': 1,
      'aggregations.contestantsLikeness': 0.08,
    },
  },
  TACTICIAN: {
    id: 'TACTICIAN',
    name: 'Tactician',
    type: 'leadershipStyle',
    group: 'leadership',
    description: 'Strategic and analytical; part assignments are strictly logic-based.',
    occurrence: 15,
    influences: {
      'personality.ambition': 5,
      'personality.sincerity': -3,
      'utilitySkills.learning': 1,
      'personality.maturity': 3,
      'aggregations.productionRatio': 0.05,
    },
  },
  QUIET_ACE: {
    id: 'QUIET_ACE',
    name: 'Quiet Ace',
    type: 'leadershipStyle',
    group: 'leadership',
    description: 'Sets a high standard through tireless hard work.',
    occurrence: 20,
    influences: {
      'personality.extroversion': -4,
      'personality.discipline': 1,
      'utilitySkills.consistency': -1,
      'aggregations.fanbaseRatio': 0.075,
    },
  },
};

export const ZODIAC_SIGNS: Dictionary<AttributeCard> = {
  ARIES: {
    id: 'ARIES',
    name: 'Aries',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The fiery Aries is a natural-born leader, known for their courage and determination. They thrive in competitive environments and are not afraid to take risks.',
    occurrence: 8,
    influences: {
      'personality.ambition': 3,
      'personality.extroversion': 2,
      'aggregations.popularityRatio': 0.07,
    },
  },
  TAURUS: {
    id: 'TAURUS',
    name: 'Taurus',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The dependable Taurus values stability and comfort. They are patient and practical, often serving as the rock of the group.',
    occurrence: 8,
    influences: {
      'personality.discipline': 3,
      'personality.gentleness': 2,
      'aggregations.popularityRatio': 0.065,
    },
  },
  GEMINI: {
    id: 'GEMINI',
    name: 'Gemini',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The adaptable Gemini is a social butterfly, known for their quick wit and versatility. They excel in communication and can easily connect with others.',
    occurrence: 8,
    influences: {
      'personality.curiosity': 3,
      'personality.extroversion': 3,
      'aggregations.popularityRatio': 0.075,
    },
  },
  CANCER: {
    id: 'CANCER',
    name: 'Cancer',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The nurturing Cancer is deeply intuitive and emotional. They are fiercely loyal to their loved ones and often take on a caregiving role within the group.',
    occurrence: 8,
    influences: {
      'personality.sensitivity': 4,
      'personality.gentleness': 3,
      'aggregations.popularityRatio': 0.08,
    },
  },
  LEO: {
    id: 'LEO',
    name: 'Leo',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The charismatic Leo loves the spotlight and is a natural performer. They are confident and ambitious, often inspiring others with their passion.',
    occurrence: 8,
    influences: {
      'personality.extroversion': 4,
      'personality.ambition': 4,
      'aggregations.popularityRatio': 0.085,
    },
  },
  VIRGO: {
    id: 'VIRGO',
    name: 'Virgo',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The meticulous Virgo is a perfectionist who pays great attention to detail. They are analytical and practical, often helping to keep the group organized.',
    occurrence: 8,
    influences: {
      'personality.discipline': 4,
      'personality.sincerity': 3,
      'aggregations.popularityRatio': 0.06,
    },
  },
  LIBRA: {
    id: 'LIBRA',
    name: 'Libra',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The charming Libra values harmony and balance. They are diplomatic and sociable, often acting as the peacemaker within the group.',
    occurrence: 8,
    influences: {
      'personality.sincerity': 4,
      'personality.extroversion': 2,
      'aggregations.popularityRatio': 0.07,
    },
  },
  SCORPIO: {
    id: 'SCORPIO',
    name: 'Scorpio',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The intense Scorpio is passionate and resourceful. They are known for their determination and can be quite mysterious.',
    occurrence: 8,
    influences: {
      'personality.ambition': 4,
      'personality.sensitivity': 2,
      'aggregations.popularityRatio': 0.075,
    },
  },
  SAGITTARIUS: {
    id: 'SAGITTARIUS',
    name: 'Sagittarius',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The adventurous Sagittarius is optimistic and loves freedom. They are enthusiastic and often bring a sense of fun to the group.',
    occurrence: 8,
    influences: {
      'personality.extroversion': 3,
      'personality.curiosity': 4,
      'aggregations.popularityRatio': 0.08,
    },
  },
  CAPRICORN: {
    id: 'CAPRICORN',
    name: 'Capricorn',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The disciplined Capricorn is ambitious and responsible. They are hardworking and often take on a leadership role within the group.',
    occurrence: 8,
    influences: {
      'personality.discipline': 5,
      'personality.ambition': 3,
      'aggregations.popularityRatio': 0.065,
    },
  },
  AQUARIUS: {
    id: 'AQUARIUS',
    name: 'Aquarius',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The innovative Aquarius is independent and intellectual. They are often seen as unconventional and are not afraid to challenge the status quo.',
    occurrence: 8,
    influences: {
      'personality.curiosity': 5,
      'personality.extroversion': -2,
      'aggregations.popularityRatio': 0.07,
    },
  },
  PISCES: {
    id: 'PISCES',
    name: 'Pisces',
    type: 'zodiacSign',
    group: 'zodiac',
    description:
      'The empathetic Pisces is artistic and intuitive. They are deeply emotional and often have a strong connection to music and creativity.',
    occurrence: 8,
    influences: {
      'personality.sensitivity': 5,
      'personality.gentleness': 4,
      'aggregations.popularityRatio': 0.075,
    },
  },
};
